/**
 * OpenApi specification - MMM
 *
 * OpenApi documentation for MMM
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@mmm.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mmm_mobile.data.entities

import com.example.mmm_mobile.data.entities.ArticleCategoryDTO

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param category 
 * @param content 
 * @param createdAt 
 * @param id 
 * @param status 
 * @param title 
 */
@Serializable
data class ArticleDTO (

    @SerialName(value = "category")
    val category: ArticleCategoryDTO? = null,

    @SerialName(value = "content")
    val content: kotlin.String? = null,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "id")
    val id: kotlin.Long? = null,

    @SerialName(value = "status")
    val status: ArticleDTO.Status? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: pUBLISHED,dRAFT
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "PUBLISHED") pUBLISHED("PUBLISHED"),
        @SerialName(value = "DRAFT") dRAFT("DRAFT");
    }
}

