/**
 * OpenApi specification - MMM
 *
 * OpenApi documentation for MMM
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@mmm.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mmm_mobile.data.entities

import com.example.mmm_mobile.data.entities.RecipeIngredientForm

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param instructions 
 * @param ingredients 
 * @param kcalPerServing 
 * @param name 
 * @param servings 
 */
@Serializable
data class CreateRecipeRequest (

    @SerialName(value = "instructions")
    val instructions: kotlin.String,

    @SerialName(value = "ingredients")
    val ingredients: kotlin.collections.List<RecipeIngredientForm>? = null,

    @SerialName(value = "kcalPerServing")
    val kcalPerServing: kotlin.Double? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "servings")
    val servings: kotlin.Int? = null

)

