/**
 * OpenApi specification - MMM
 *
 * OpenApi documentation for MMM
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@mmm.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mmm_mobile.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param energyKcalPer100g 
 * @param fatPer100g 
 * @param fiberPer100g 
 * @param proteinsPer100g 
 * @param saltPer100g 
 * @param sodiumPer100g 
 * @param sugarsPer100g 
 */
@Serializable
data class CreateNutrimentRequest (

    @SerialName(value = "energyKcalPer100g")
    val energyKcalPer100g: kotlin.Double,

    @SerialName(value = "fatPer100g")
    val fatPer100g: kotlin.Double,

    @SerialName(value = "fiberPer100g")
    val fiberPer100g: kotlin.Double,

    @SerialName(value = "proteinsPer100g")
    val proteinsPer100g: kotlin.Double,

    @SerialName(value = "saltPer100g")
    val saltPer100g: kotlin.Double,

    @SerialName(value = "sodiumPer100g")
    val sodiumPer100g: kotlin.Double,

    @SerialName(value = "sugarsPer100g")
    val sugarsPer100g: kotlin.Double

)

