/**
 * OpenApi specification - MMM
 *
 * OpenApi documentation for MMM
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@mmm.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mmm_mobile.data.entities

import com.example.mmm_mobile.data.entities.RecipeIngredient

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param recipeIngredients 
 */
@Serializable
data class Ingredient (

    @SerialName(value = "id")
    val id: kotlin.Long? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "recipeIngredients")
    val recipeIngredients: kotlin.collections.Set<RecipeIngredient>? = null

)

