/**
 * OpenApi specification - MMM
 *
 * OpenApi documentation for MMM
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@mmm.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mmm_mobile.data.entities

import com.example.mmm_mobile.data.entities.PageableObject
import com.example.mmm_mobile.data.entities.SortObject

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param content 
 * @param empty 
 * @param first 
 * @param last 
 * @param number 
 * @param numberOfElements 
 * @param pageable 
 * @param propertySize 
 * @param sort 
 * @param totalElements 
 * @param totalPages 
 */
@Serializable
data class Page (

    @SerialName(value = "content")
    val content: kotlin.collections.List<@Contextual kotlin.Any>? = null,

    @SerialName(value = "empty")
    val empty: kotlin.Boolean? = null,

    @SerialName(value = "first")
    val first: kotlin.Boolean? = null,

    @SerialName(value = "last")
    val last: kotlin.Boolean? = null,

    @SerialName(value = "number")
    val number: kotlin.Int? = null,

    @SerialName(value = "numberOfElements")
    val numberOfElements: kotlin.Int? = null,

    @SerialName(value = "pageable")
    val pageable: PageableObject? = null,

    @SerialName(value = "size")
    val propertySize: kotlin.Int? = null,

    @SerialName(value = "sort")
    val sort: SortObject? = null,

    @SerialName(value = "totalElements")
    val totalElements: kotlin.Long? = null,

    @SerialName(value = "totalPages")
    val totalPages: kotlin.Int? = null

)

