/**
 * OpenApi specification - MMM
 *
 * OpenApi documentation for MMM
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@mmm.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mmm_mobile.data.entities

import com.example.mmm_mobile.data.entities.SortObject

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param offset 
 * @param pageNumber 
 * @param pageSize 
 * @param paged 
 * @param sort 
 * @param unpaged 
 */
@Serializable
data class PageableObject (

    @SerialName(value = "offset")
    val offset: kotlin.Long? = null,

    @SerialName(value = "pageNumber")
    val pageNumber: kotlin.Int? = null,

    @SerialName(value = "pageSize")
    val pageSize: kotlin.Int? = null,

    @SerialName(value = "paged")
    val paged: kotlin.Boolean? = null,

    @SerialName(value = "sort")
    val sort: SortObject? = null,

    @SerialName(value = "unpaged")
    val unpaged: kotlin.Boolean? = null

)

