/**
 * OpenApi specification - MMM
 *
 * OpenApi documentation for MMM
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@mmm.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mmm_mobile.data.entities

import com.example.mmm_mobile.data.entities.Ingredient
import com.example.mmm_mobile.data.entities.Recipe

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param amount 
 * @param id 
 * @param ingredient 
 * @param recipe 
 * @param unit 
 */
@Serializable
data class RecipeIngredient (

    @SerialName(value = "amount")
    val amount: kotlin.Double? = null,

    @SerialName(value = "id")
    val id: kotlin.Long? = null,

    @SerialName(value = "ingredient")
    val ingredient: Ingredient? = null,

    @SerialName(value = "recipe")
    val recipe: Recipe? = null,

    @SerialName(value = "unit")
    val unit: RecipeIngredient.Unit? = null

) {

    /**
     * 
     *
     * Values: g,mL,tSP,tBSP,cUP,pIECE
     */
    @Serializable
    enum class Unit(val value: kotlin.String) {
        @SerialName(value = "G") g("G"),
        @SerialName(value = "ML") mL("ML"),
        @SerialName(value = "TSP") tSP("TSP"),
        @SerialName(value = "TBSP") tBSP("TBSP"),
        @SerialName(value = "CUP") cUP("CUP"),
        @SerialName(value = "PIECE") pIECE("PIECE");
    }
}

