/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.RecipeIngredientForm

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param instructions 
 * @param ingredients 
 * @param kcalPerServing 
 * @param name 
 * @param servings 
 */


data class CreateRecipeRequest (

    @Json(name = "instructions")
    val instructions: kotlin.String,

    @Json(name = "ingredients")
    val ingredients: kotlin.collections.List<RecipeIngredientForm>? = null,

    @Json(name = "kcalPerServing")
    val kcalPerServing: kotlin.Double? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "servings")
    val servings: kotlin.Int? = null

)

