/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param page 
 * @param propertySize 
 * @param sort 
 */


data class Pageable (

    @Json(name = "page")
    val page: kotlin.Int? = null,

    @Json(name = "size")
    val propertySize: kotlin.Int? = null,

    @Json(name = "sort")
    val sort: kotlin.collections.List<kotlin.String>? = null

)

