/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param fromPalmOil 
 * @param id 
 * @param name 
 * @param vegan 
 * @param vegetarian 
 */


data class ProductIngredient (

    @Json(name = "fromPalmOil")
    val fromPalmOil: kotlin.Boolean? = null,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "vegan")
    val vegan: kotlin.Boolean? = null,

    @Json(name = "vegetarian")
    val vegetarian: kotlin.Boolean? = null

)

