/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param propertySize 
 * @param url 
 */


data class ProductImageDTO (

    @Json(name = "size")
    val propertySize: ProductImageDTO.PropertySize,

    @Json(name = "url")
    val url: kotlin.String

) {

    /**
     * 
     *
     * Values: bIG,sMALL,tHUMBNAIL
     */
    @JsonClass(generateAdapter = false)
    enum class PropertySize(val value: kotlin.String) {
        @Json(name = "BIG") BIG("BIG"),
        @Json(name = "SMALL") SMALL("SMALL"),
        @Json(name = "THUMBNAIL") THUMBNAIL("THUMBNAIL");
    }
}

