/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ProductImageDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param barcode 
 * @param id 
 * @param image 
 * @param name 
 * @param novaGroup 
 * @param nutriScore 
 * @param quantity 
 */


data class ProductToListDTO (

    @Json(name = "barcode")
    val barcode: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Long,

    @Json(name = "image")
    val image: ProductImageDTO? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "novaGroup")
    val novaGroup: kotlin.Int? = null,

    @Json(name = "nutriScore")
    val nutriScore: kotlin.Int? = null,

    @Json(name = "quantity")
    val quantity: kotlin.String? = null

)

