/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param fullName 
 * @param id 
 * @param rating 
 * @param userId 
 * @param comment 
 */


data class RecipeReviewDTO (

    @Json(name = "fullName")
    val fullName: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Long,

    @Json(name = "rating")
    val rating: kotlin.Double,

    @Json(name = "userId")
    val userId: kotlin.Long,

    @Json(name = "comment")
    val comment: kotlin.String? = null

)

