/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param amount 
 * @param ingredientId 
 * @param name 
 * @param unit 
 */


data class RecipeIngredientDTO (

    @Json(name = "amount")
    val amount: kotlin.Double? = null,

    @Json(name = "ingredientId")
    val ingredientId: kotlin.Long? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "unit")
    val unit: RecipeIngredientDTO.Unit? = null

) {

    /**
     * 
     *
     * Values: g,mL,tSP,tBSP,cUP,pIECE
     */
    @JsonClass(generateAdapter = false)
    enum class Unit(val value: kotlin.String) {
        @Json(name = "G") g("G"),
        @Json(name = "ML") mL("ML"),
        @Json(name = "TSP") tSP("TSP"),
        @Json(name = "TBSP") tBSP("TBSP"),
        @Json(name = "CUP") cUP("CUP"),
        @Json(name = "PIECE") pIECE("PIECE");
    }
}

