/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Ingredient
import org.openapitools.client.models.Recipe

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param amount 
 * @param id 
 * @param ingredient 
 * @param recipe 
 * @param unit 
 */


data class RecipeIngredient (

    @Json(name = "amount")
    val amount: kotlin.Double? = null,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "ingredient")
    val ingredient: Ingredient? = null,

    @Json(name = "recipe")
    val recipe: Recipe? = null,

    @Json(name = "unit")
    val unit: RecipeIngredient.Unit? = null

) {

    /**
     * 
     *
     * Values: g,mL,tSP,tBSP,cUP,pIECE,pINCH,pACKAGE,hANDFUL,jAR,cAN,bUNCH,sLICE,oTHER
     */
    @JsonClass(generateAdapter = false)
    enum class Unit(val value: kotlin.String) {
        @Json(name = "G") G("G"),
        @Json(name = "ML") ML("ML"),
        @Json(name = "TSP") TSP("TSP"),
        @Json(name = "TBSP") TBSP("TBSP"),
        @Json(name = "CUP") CUP("CUP"),
        @Json(name = "PIECE") PIECE("PIECE"),
        @Json(name = "PINCH") PINCH("PINCH"),
        @Json(name = "PACKAGE") PACKAGE("PACKAGE"),
        @Json(name = "HANDFUL") HANDFUL("HANDFUL"),
        @Json(name = "JAR") JAR("JAR"),
        @Json(name = "CAN") CAN("CAN"),
        @Json(name = "BUNCH") BUNCH("BUNCH"),
        @Json(name = "SLICE") SLICE("SLICE"),
        @Json(name = "OTHER") OTHER("OTHER");
    }
}

