/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param amount 
 * @param ingredientId 
 * @param unit 
 */


data class RecipeIngredientForm (

    @Json(name = "amount")
    val amount: kotlin.Double,

    @Json(name = "ingredientId")
    val ingredientId: kotlin.Long,

    @Json(name = "unit")
    val unit: RecipeIngredientForm.Unit

) {

    /**
     * 
     *
     * Values: g,mL,tSP,tBSP,cUP,pIECE,pINCH,pACKAGE,hANDFUL,jAR,cAN,bUNCH,sLICE,oTHER
     */
    @JsonClass(generateAdapter = false)
    enum class Unit(val value: kotlin.String) {
        @Json(name = "G") g("G"),
        @Json(name = "ML") mL("ML"),
        @Json(name = "TSP") tSP("TSP"),
        @Json(name = "TBSP") tBSP("TBSP"),
        @Json(name = "CUP") cUP("CUP"),
        @Json(name = "PIECE") pIECE("PIECE"),
        @Json(name = "PINCH") pINCH("PINCH"),
        @Json(name = "PACKAGE") pACKAGE("PACKAGE"),
        @Json(name = "HANDFUL") hANDFUL("HANDFUL"),
        @Json(name = "JAR") jAR("JAR"),
        @Json(name = "CAN") cAN("CAN"),
        @Json(name = "BUNCH") bUNCH("BUNCH"),
        @Json(name = "SLICE") sLICE("SLICE"),
        @Json(name = "OTHER") oTHER("OTHER");
    }
}

